import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const collectives = sqliteTable('collectives', { id:text().primaryKey(), name:text().notNull(), color:text().notNull(), stripeAccount:text('stripe_account'), createdAt:integer('created_at').notNull() });
export const members = sqliteTable('members', { id:text().primaryKey(), email:text().notNull(), collectiveId:text('collective_id').references(()=>collectives.id), role:text().notNull() }, t=>[uniqueIndex('members_scope').on(t.email,t.collectiveId)]);
export const events = sqliteTable('events', {
 id:text().primaryKey(), collectiveId:text('collective_id').notNull().references(()=>collectives.id), name:text().notNull(), description:text().notNull().default(''), location:text().notNull(), timezone:text().notNull().default('Europe/Paris'), startsAt:integer('starts_at').notNull(), doorsAt:integer('doors_at').notNull(), cancelUntil:integer('cancel_until').notNull(), status:text().notNull().default('draft'), holdMinutes:integer('hold_minutes').notNull().default(15), maxQuantity:integer('max_quantity').notNull().default(6), waitHours:integer('wait_hours').notNull().default(12), urgentWaitHours:integer('urgent_wait_hours').notNull().default(2), createdAt:integer('created_at').notNull()
}, t=>[index('events_collective').on(t.collectiveId)]);
export const types = sqliteTable('ticket_types', {
 id:text().primaryKey(), eventId:text('event_id').notNull().references(()=>events.id), name:text().notNull(), price:integer().notNull(), capacity:integer().notNull(), held:integer().notNull().default(0), sold:integer().notNull().default(0), earlyPrice:integer('early_price'), earlyUntil:integer('early_until')
}, t=>[index('types_event').on(t.eventId),check('stock_bounds',sql`${t.held} >= 0 AND ${t.sold} >= 0 AND ${t.capacity} >= ${t.held} + ${t.sold}`),check('price_positive',sql`${t.price} >= 0`)]);
export const orders = sqliteTable('orders', {
 id:text().primaryKey(), eventId:text('event_id').notNull().references(()=>events.id), email:text().notNull(), name:text().notNull(), token:text().notNull().unique(), status:text().notNull().default('pending'), total:integer().notNull(), expiresAt:integer('expires_at').notNull(), createdAt:integer('created_at').notNull(), paidAt:integer('paid_at'), paymentId:text('payment_id').unique(), checkoutId:text('checkout_id'), refunded:integer().notNull().default(0), demo:integer().notNull().default(0)
}, t=>[index('orders_expiry').on(t.status,t.expiresAt),index('orders_event').on(t.eventId)]);
export const items = sqliteTable('order_items', { id:text().primaryKey(), orderId:text('order_id').notNull().references(()=>orders.id), typeId:text('type_id').notNull().references(()=>types.id), quantity:integer().notNull(), unitPrice:integer('unit_price').notNull() },t=>[index('items_order').on(t.orderId),check('quantity_positive',sql`${t.quantity}>0`)]);
export const tickets = sqliteTable('tickets', { id:text().primaryKey(), orderId:text('order_id').notNull().references(()=>orders.id), typeId:text('type_id').notNull().references(()=>types.id), code:text().notNull().unique(), status:text().notNull().default('valid'), scannedAt:integer('scanned_at'), deviceId:text('device_id'), refundAmount:integer('refund_amount').notNull().default(0) },t=>[index('tickets_order').on(t.orderId)]);
export const payments = sqliteTable('payments',{id:text().primaryKey(),orderId:text('order_id').notNull().references(()=>orders.id),amount:integer().notNull(),status:text().notNull(),createdAt:integer('created_at').notNull()});
export const waitlist = sqliteTable('waitlist', { id:text().primaryKey(), typeId:text('type_id').notNull().references(()=>types.id), email:text().notNull(), name:text().notNull(), quantity:integer().notNull(), status:text().notNull().default('waiting'), orderId:text('order_id').references(()=>orders.id), createdAt:integer('created_at').notNull() },t=>[index('waitlist_fifo').on(t.typeId,t.status,t.createdAt)]);
export const scannerLinks = sqliteTable('scanner_links',{id:text().primaryKey(),eventId:text('event_id').notNull().references(()=>events.id),token:text().notNull().unique(),validFrom:integer('valid_from').notNull(),validUntil:integer('valid_until').notNull(),createdAt:integer('created_at').notNull()});
export const jobs = sqliteTable('jobs',{id:text().primaryKey(),kind:text().notNull(),payload:text().notNull(),status:text().notNull().default('pending'),attempts:integer().notNull().default(0),nextAt:integer('next_at').notNull(),createdAt:integer('created_at').notNull(),error:text()},t=>[index('jobs_pending').on(t.status,t.nextAt)]);
export const audit = sqliteTable('audit',{id:text().primaryKey(),collectiveId:text('collective_id'),actor:text().notNull(),action:text().notNull(),subject:text().notNull(),detail:text().notNull(),createdAt:integer('created_at').notNull()});
export const challenges = sqliteTable('challenges',{id:text().primaryKey(),email:text().notNull(),codeHash:text('code_hash').notNull(),expiresAt:integer('expires_at').notNull(),attempts:integer().notNull().default(0),used:integer().notNull().default(0)},t=>[index('challenge_email').on(t.email,t.expiresAt)]);
export const sessions = sqliteTable('sessions',{token:text().primaryKey(),email:text().notNull(),expiresAt:integer('expires_at').notNull()});
export const settings = sqliteTable('settings',{key:text().primaryKey(),value:text().notNull()});
