'use client';
import { useState,useEffect } from 'react';
import { Ticket,MapPin,CalendarDays,Clock3,Minus,Plus,Download,Check,ShoppingBag,ChevronLeft } from 'lucide-react';
import { api,money,date,labels } from '@/lib/client';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel } from '@/components/ui/alert-dialog';
export function PublicShell({children,mode}:any){return <div className="public-app"><header className="public-header"><a className="brand" href="/billetterie"><span className="brand-mark"><Ticket size={23}/></span><span>passage<span className="brand-subtitle">BILLETTERIE</span></span></a><a className="text-link" href="/">Espace organisateur</a></header>{mode==='demo'&&<div className="public-demo">Démonstration · Aucun paiement réel, aucun e-mail envoyé</div>}{children}<footer className="public-footer">Une place. Un billet. Un rendez-vous.</footer><Toaster position="bottom-center" richColors/></div>;}
export function Catalogue(){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{api('events').then(setData).catch(e=>setError(e.message));},[]);
 return <PublicShell mode={data?.mode}><main className="catalogue"><p className="eyebrow">LES RENDEZ-VOUS DES COLLECTIFS</p><h1>On se retrouve bientôt.</h1><p className="page-description">Choisissez votre événement et réservez vos places.</p>{error&&<p className="form-error" role="alert">{error}</p>}{!data&&!error&&<p>Chargement des événements…</p>}<div className="catalogue-grid">{data?.events.filter((e:any)=>e.status!=='cancelled'&&e.status!=='finished'&&e.doors_at>Date.now()).map((e:any)=><a className="catalogue-card" href={'/evenement/'+e.id} key={e.id}><div className="catalogue-date" style={{background:e.color}}><span>{date(e.starts_at,e.timezone,{month:'long'})}</span><strong>{date(e.starts_at,e.timezone,{day:'2-digit'})}</strong><small>{e.collective_name}</small><Ticket size={55}/></div><div className="catalogue-info"><p className="eyebrow">{e.description}</p><h2>{e.name}</h2><p><MapPin size={15}/>{e.location}</p><div className="catalogue-bottom"><span>À partir de <strong>{money(Math.min(...e.types.map((t:any)=>t.early_until>Date.now()&&t.early_price!=null?t.early_price:t.price)))}</strong></span><span className="button primary">Réserver</span></div></div></a>)}</div>{data&&data.events.length===0&&<p>Aucun événement en vente pour le moment.</p>}</main></PublicShell>;
}
export function Booking({id}:any){
 const [event,setEvent]=useState<any>(null),[mode,setMode]=useState(''),[quantities,setQuantities]=useState<Record<string,number>>({}),[waiting,setWaiting]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[subscribed,setSubscribed]=useState(false);
 const load=()=>api('events/'+id).then(r=>{setEvent(r.events[0]);setMode(r.mode);if(!r.events[0])setError('Cet événement est introuvable.');});
 useEffect(()=>{load().catch(e=>setError(e.message));const timer=setInterval(()=>load().catch(()=>{}),15000);return ()=>clearInterval(timer);},[id]);
 const price=(t:any)=>t.early_until>Date.now()&&t.early_price!=null?t.early_price:t.price;
 const qty=Object.values(quantities).reduce((s,n)=>s+n,0),total=event?.types.reduce((s:number,t:any)=>s+price(t)*(quantities[t.id]||0),0)||0;
 const closed=event&&(event.status!=='on_sale'||event.doors_at<=Date.now());
 const waitingType=event?.types.find((type:{id:string;name:string;waitlist_limit?:number})=>type.id===waiting);
 return <PublicShell mode={mode}><main className="booking-layout"><section className="booking-event"><a className="text-link" href="/billetterie"><ChevronLeft size={17}/>Tous les événements</a>{event&&<><div className="booking-collective"><span>{event.collective_name}</span><Ticket size={27}/></div><p className="eyebrow">{event.description}</p><h1>{event.name}</h1><div className="event-facts"><p><CalendarDays size={20}/>{date(event.starts_at,event.timezone,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><p><Clock3 size={20}/>Début à {date(event.starts_at,event.timezone,{hour:'2-digit',minute:'2-digit'})} · portes à {date(event.doors_at,event.timezone,{hour:'2-digit',minute:'2-digit'})}</p><p><MapPin size={20}/>{event.location}</p></div><div className="booking-note"><Ticket size={21}/><p>Billets non nominatifs · {event.max_quantity} places maximum par commande.<br/>Annulation possible jusqu’au {date(event.cancel_until,event.timezone,{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}.</p></div></>}</section><section className="booking-card"><h2>{waiting?'Me prévenir':'Vos places'}</h2>{!event&&!error&&<p>Chargement…</p>}{closed&&<div className="error-banner">La réservation est fermée pour cet événement.</div>}{event&&!waiting&&<div className="booking-types">{event.types.map((t:any)=><div className="booking-type" key={t.id}><div><h3>{t.name}</h3><strong>{money(price(t))}</strong>{price(t)!==t.price&&<del>{money(t.price)}</del>}<small>{t.available>0?t.available+' places disponibles':'Complet'}</small>{price(t)!==t.price&&<small>Tarif early jusqu’au {date(t.early_until,event.timezone,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small>}</div>{t.available>0&&!closed?<div className="quantity-stepper"><button disabled={!quantities[t.id]} aria-label={'Retirer une place '+t.name} onClick={()=>setQuantities({...quantities,[t.id]:(quantities[t.id]||0)-1})}><Minus size={16}/></button><span>{quantities[t.id]||0}</span><button disabled={qty>=event.max_quantity||(quantities[t.id]||0)>=t.available} aria-label={'Ajouter une place '+t.name} onClick={()=>setQuantities({...quantities,[t.id]:(quantities[t.id]||0)+1})}><Plus size={16}/></button></div>:!closed?<button className="button secondary" onClick={()=>{setWaiting(t.id);setError('');}}>Me prévenir</button>:null}</div>)}</div>}
 {subscribed?<div className="success-message"><Check size={32}/><h3>Vous êtes sur la liste.</h3><p>Vous recevrez un e-mail lorsque vos places seront disponibles.</p>{mode==='demo'&&<small>En démonstration, la demande est enregistrée sans envoi d’e-mail.</small>}<button className="button secondary" onClick={()=>{setWaiting('');setSubscribed(false);}}>Revenir à l’événement</button></div>:event&&!closed&&<form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{if(waiting){await api('waitlist',{typeId:waiting,name:f.get('name'),email:f.get('email'),quantity:Number(f.get('quantity'))});setSubscribed(true);}else{const r=await api('reserve',{eventId:id,name:f.get('name'),email:f.get('email'),items:event.types.filter((t:any)=>quantities[t.id]).map((t:any)=>({typeId:t.id,quantity:quantities[t.id]}))});location.href='/commande/'+r.token;}}catch(err:any){setError(err.message);load().catch(()=>{});}finally{setBusy(false);}}}>
 {waiting&&<><p>{waitingType?.name} · les places seront proposées dans l’ordre d’inscription.</p><label className="field"><span>Nombre de places souhaitées</span><input name="quantity" type="number" min="1" max={waitingType?.waitlist_limit??event.max_quantity} defaultValue="1" required/></label></>}
 <label className="field"><span>Votre nom</span><input name="name" autoComplete="name" required maxLength={120}/></label><label className="field"><span>Votre adresse e-mail</span><input name="email" type="email" autoComplete="email" required/></label>{!waiting&&<div className="booking-total"><span>{qty} place{qty>1?'s':''}</span><strong>{money(total)}</strong></div>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full-width" disabled={busy||(!waiting&&!qty)}>{busy?'Un instant…':waiting?'M’inscrire à la liste':'Réserver mes places'}</button>{waiting?<button type="button" className="text-button" onClick={()=>setWaiting('')}>Revenir aux places</button>:<p className="checkout-note">Vos places seront retenues pendant {event.hold_minutes} minutes, le temps de payer. Aucun compte à créer.</p>}</form>}{!event&&error&&<p className="form-error" role="alert">{error}</p>}</section></main></PublicShell>;
}
export function Order({token}:any){
 const [order,setOrder]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(Date.now()),[confirm,setConfirm]=useState<any>(null);
 const load=()=>api('orders/'+token).then(setOrder);
 useEffect(()=>{load().catch(e=>setError(e.message));const timer=setInterval(()=>{setTick(Date.now());load().catch(()=>{});},5000);return ()=>clearInterval(timer);},[token]);
 const seconds=order?Math.max(0,Math.floor((order.expires_at-tick)/1000)):0;
 return <PublicShell mode={order?.demo?'demo':'live'}><main className="order-page">{error&&<p className="form-error" role="alert">{error}</p>}{!order&&!error&&<p>Chargement de votre commande…</p>}{order&&<>
 <p className="eyebrow">VOTRE COMMANDE · {order.id.slice(0,8).toUpperCase()}</p><h1>{order.status==='paid'?'Vos billets sont prêts.':order.status==='pending'?'Vos places vous attendent.':labels[order.status]+'.'}</h1><p className="page-description">{order.event.name} · {date(order.event.starts_at,order.event.timezone)} · {order.event.location}</p>
 <div className="order-summary"><ShoppingBag size={22}/><div>{order.items.map((i:any)=><p key={i.id}>{i.quantity} × {i.type_name} <span>{money(i.unit_price*i.quantity)}</span></p>)}<small>{order.email}</small></div><strong>{money(order.total)}</strong></div>
 {order.status==='pending'&&<section className="payment-box"><div className="countdown"><Clock3 size={20}/><span>Places retenues pendant <strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></span></div><button className="button primary full-width" disabled={busy||seconds===0} onClick={async()=>{setBusy(true);setError('');try{const r=await api('orders/'+token+'/checkout',{});if(r.url)location.href=r.url;else await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Un instant…':order.demo?'Simuler le paiement · '+money(order.total):'Payer par carte · '+money(order.total)}</button><p>{order.demo?'Paiement fictif : aucun prélèvement ne sera effectué.':'Le paiement s’effectue chez le prestataire. Votre billet sera émis après confirmation du paiement.'}</p><button className="text-button" disabled={busy} onClick={()=>setConfirm({kind:'release'})}>Libérer ma réservation</button></section>}
 {order.tickets.length>0&&<><div className="ticket-downloads"><a className="button primary" href={'/api/orders/'+token+'/pdf'}><Download size={17}/>Télécharger les billets PDF</a><a className="button secondary" href={'/api/orders/'+token+'/calendar'}><CalendarDays size={17}/>Ajouter à mon agenda</a></div><p className="muted">Conservez vos billets PDF sur votre téléphone pour les présenter sans connexion.</p><div className="tickets-grid">{order.tickets.map((t:any)=><article className={'ticket-card '+(t.status==='cancelled'?'cancelled':'')} key={t.id}><div className="ticket-card-header"><Ticket size={24}/><span>{order.event.collective_name}</span></div><h2>{order.event.name}</h2><p>{t.type_name} · Billet {t.id.slice(0,8).toUpperCase()}</p><img src={t.qr} alt={'QR code du billet '+t.id.slice(0,8)} width={240} height={240}/><strong className="ticket-state">{t.status==='cancelled'?'Billet annulé':t.scanned_at?'Entrée déjà validée':'Valable pour une entrée'}</strong>{t.status==='valid'&&!t.scanned_at&&tick<order.event.cancel_until&&<button className="text-button danger" onClick={()=>setConfirm({kind:'ticket',id:t.id})}>Annuler cette place</button>}{order.demo&&<small>DÉMONSTRATION · SANS VALEUR</small>}</article>)}</div></>}
 {['expired','cancelled'].includes(order.status)&&!order.tickets.length&&<div className="info-note"><Clock3 size={22}/><p>Les places ont été libérées. Vous pouvez consulter l’événement pour réserver à nouveau.</p><a className="button secondary" href={'/evenement/'+order.event_id}>Voir l’événement</a></div>}
 {order.refunded>0&&<p className="success-message">{money(order.refunded)} remboursés.</p>}
 </>}</main><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.kind==='ticket'?'Annuler et rembourser cette place ?':'Libérer vos places ?'}</AlertDialogTitle><AlertDialogDescription>{confirm?.kind==='ticket'?'Ce billet sera invalidé immédiatement. Le remboursement intégral sera déclenché.':'Votre réservation prendra fin et les places seront proposées aux autres acheteurs.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Conserver</AlertDialogCancel><AlertDialogAction onClick={async()=>{try{await api('orders/'+token+'/'+(confirm.kind==='ticket'?'cancel-ticket':'cancel'),confirm.kind==='ticket'?{ticketId:confirm.id}:{});await load();toast.success('Annulation enregistrée.');}catch(e:any){toast.error(e.message);}setConfirm(null);}}>Confirmer l’annulation</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></PublicShell>;
}
